# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: qm
# app and org for use with dashboard.serverless.com
app: api-app
org: firminsa

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

plugins:
  - serverless-python-requirements

# you can add packaging information here
package:
  #  include:
  #    - include-me.py
  #    - include-me-dir/**
  exclude:
    - swagger/**
    - .idea/**
    - LICENSE
    - package-lock.json
    - package.json
    - Pipfile
    - venv/**
    - node_modules/**
    - server.py
    - generator.py

functions:
  login:
    handler: api/handlers/account.login
    events:
      - http:
          path: qm/login
          method: post
          cors: true

  register:
    handler: api/handlers/account.register
    events:
      - http:
          path: qm/register
          method: post
          cors: true

  create_quiz:
    handler: api/handlers/quiz.create_quiz
    events:
      - http:
          path: qm/quizzes
          method: post
          cors: true

  delete_quiz:
    handler: api/handlers/quiz.delete_quiz
    events:
      - http:
          path: qm/quizzes/{quiz_id}
          method: put
          cors: true

  update_quiz:
    handler: api/handlers/quiz.delete_quiz
    events:
      - http:
          path: qm/quizzes/{quiz_id}
          method: delete
          cors: true

  create_question:
    handler: api/handlers/question.create_question
    events:
      - http:
          path: qm/questions
          method: post
          cors: true

  delete_question:
    handler: api/handlers/question.delete_question
    events:
      - http:
          path: qm/questions/{question_id}
          method: delete
          cors: true

  update_question:
    handler: api/handlers/question.update_question
    events:
      - http:
          path: qm/questions/{question_id}
          method: put
          cors: true

  create_flashcard_deck:
    handler: api/handlers/flashcard_deck.create_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks
          method: post
          cors: true

  create_flashcard:
    handler: api/handlers/flashcard.create_flashcard
    events:
      - http:
          path: qm/flashcards
          method: post
          cors: true

  delete_flashcard:
    handler: api/handlers/flashcard.delete_flashcard
    events:
      - http:
          path: qm/flashcards/{flashcard_id}
          method: delete
          cors: true

  delete_flashcard_deck:
    handler: api/handlers/flashcard_deck.delete_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks/{flashcard_deck_id}
          method: delete
          cors: true

  update_flashcard_deck:
    handler: api/handlers/flashcard_deck.update_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks/{flashcard_deck_id}
          method: put
          cors: true

  get_user_quizzes:
    handler: api/handlers/quiz.get_by_user_id
    events:
      - http:
          path: qm/users/{user_id}/quizzes
          method: get
          cors: true
          request:
            paths:
              user_id: true

  get_user_flashcard_decks:
    handler: api/handlers/flashcard_deck.get_by_user_id
    events:
      - http:
          path: qm/users/{user_id}/flashcard-decks
          method: get
          cors: true
          request:
            paths:
              user_id: true