# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: qm
# app and org for use with dashboard.serverless.com
app: api-app
org: firminsa

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.7
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

#  stage: dev
#  region: us-east-1


plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePipenv: false
    pythonBin: "python"
    fileName: "prod-requirements.txt"

# you can add packaging information here
package:
  #  include:
  #    - include-me.py
  #    - include-me-dir/**
  exclude:
    - swagger/**
    - .idea/**
    - LICENSE
    - package-lock.json
    - package.json
    - Pipfile
    - venv/**
    - node_modules/**
    - server.py
    - generator.py

functions:
  login:
    handler: api/handlers/account.login
    events:
      - http:
          path: qm/login
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  register:
    handler: api/handlers/account.register
    events:
      - http:
          path: qm/register
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  create_quiz:
    handler: api/handlers/quiz.create_quiz
    events:
      - http:
          path: qm/quizzes
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  get_quiz:
    handler: api/handlers/quiz.get_quiz_by_id
    events:
      - http:
          path: qm/quizzes/{quiz_id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
          request:
            paths:
              quiz_id: true

  delete_quiz:
    handler: api/handlers/quiz.delete_quiz
    events:
      - http:
          path: qm/quizzes/{quiz_id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  update_quiz:
    handler: api/handlers/quiz.update_quiz
    events:
      - http:
          path: qm/quizzes
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  create_question:
    handler: api/handlers/question.create_question
    events:
      - http:
          path: qm/questions
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  delete_question:
    handler: api/handlers/question.delete_question
    events:
      - http:
          path: qm/questions/{question_id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  update_question:
    handler: api/handlers/question.update_question
    events:
      - http:
          path: qm/questions
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  create_flashcard_deck:
    handler: api/handlers/flashcard_deck.create_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  get_flashcard_deck:
    handler: api/handlers/flashcard_deck.get_by_flashcard_deck_id
    events:
      - http:
          path: qm/flashcard-decks/{flashcard_deck_id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
          request:
            paths:
              flashcard_deck_id: true

  create_flashcard:
    handler: api/handlers/flashcard.create_flashcard
    events:
      - http:
          path: qm/flashcards
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  delete_flashcard:
    handler: api/handlers/flashcard.delete_flashcard
    events:
      - http:
          path: qm/flashcards/{flashcard_id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  delete_flashcard_deck:
    handler: api/handlers/flashcard_deck.delete_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks/{flashcard_deck_id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  update_flashcard_deck:
    handler: api/handlers/flashcard_deck.update_flashcard_deck
    events:
      - http:
          path: qm/flashcard-decks/{flashcard_deck_id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin

  get_user_quizzes:
    handler: api/handlers/quiz.get_by_user_id
    events:
      - http:
          path: qm/users/{user_id}/quizzes
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
          request:
            paths:
              user_id: true

  get_user_flashcard_decks:
    handler: api/handlers/flashcard_deck.get_by_user_id
    events:
      - http:
          path: qm/users/{user_id}/flashcard-decks
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
          request:
            paths:
              user_id: true